## Criando uma Rede Neural com PyTorch

Usando o dataset da Iris Flowers do Scikit Learn (que está no formato numpy), nós construímos um classificador linear em PyTorch.nn para prever que espécie de flor é. Começamos carregando o dataset e visualizando as propriedades do mesmo.

In [25]:
from sklearn.datasets import load_iris
iris_data = load_iris()
features, pre_labels = iris_data.data, iris_data.target

In [26]:
features, pre_labels

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [27]:
print(type(features))

<class 'numpy.ndarray'>


O dataset da iris é organizado pelas labels. Então, precisamos embaralhar o dataset para que nosso modelo possa aprender ou ajustar os dados adequadamente. Antes de embaralharmos os dados, nós precisa fazer algum pré-processamento de dados.

## Pré-processamento das labels em um array

Nós vamos converter as classes em um array. Por exemplo, a classe[0] será [1,0,0]. Depois fazemos um "casting" pra array de numpy para melhor computação e memória.

In [28]:
labels = []
for num in range(len(pre_labels)):
    if pre_labels[num] == 0:
        labels.append([1, 0, 0])
    if pre_labels[num] == 1:
        labels.append([0, 1, 0])
    if pre_labels[num] == 2:
        labels.append([0, 0, 1])

In [29]:
import numpy as np
labels = np.array(labels, dtype = int)

## Dividir o dataset em treinamento e teste

Nós importamos uma função do sci-kit learn para dividir o dataset em treinamento e teste.

In [30]:
from sklearn.model_selection import train_test_split
feature_train, feature_test, labels_train, labels_test = train_test_split(features, labels, shuffle=True)

In [17]:
print(len(feature_train))
print(len(feature_test))

112
38


In [25]:
# feature_train, feature_test, labels_train, labels_test
# Dividindo os dados em 70% - 30% no conjunto de treinamento e no conjunto de teste
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.30, random_state=0)

In [26]:
print(len(x_train))
print(len(x_test))

105
45


## Importando PyTorch

In [31]:
import torch
import torch.nn as nn
import torch.utils.data as utils
import torch.utils.data as td
from torch.autograd import Variable 

## Preparando os dados para o PyTorch

O PyTorch utiliza data loaders para carregar dados de treinamento e validação em lotes. Já carregamos os dados nos arrays do NumPy, mas precisamos agrupá-los nos conjuntos de dados PyTorch (nos quais os dados são convertidos em Tensors do PyTorch) e criar loaders para ler lotes desses conjuntos de dados.

In [67]:
#feature_train = torch.Tensor(x_train).float()
#labels_train = torch.Tensor(y_train).long()
#train_ds = utils.TensorDataset(feature_train, labels_train)
#train_loader = td.DataLoader(train_ds, batch_size=10, shuffle=False, num_workers=1)

In [32]:
feature_train_v = Variable(torch.FloatTensor(feature_train), requires_grad = False)
labels_train_v = Variable(torch.FloatTensor(labels_train), requires_grad = False)
feature_test_v = Variable(torch.FloatTensor(feature_test), requires_grad = False)
labels_test_v = Variable(torch.FloatTensor(labels_test), requires_grad = False)

In [39]:
print (feature_train[::10])

tensor([[5.0000, 2.0000, 3.5000, 1.0000],
        [6.3000, 2.8000, 5.1000, 1.5000],
        [5.5000, 2.5000, 4.0000, 1.3000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [6.5000, 3.0000, 5.8000, 2.2000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 2.4000, 3.3000, 1.0000],
        [5.0000, 3.3000, 1.4000, 0.2000],
        [5.5000, 2.4000, 3.7000, 1.0000],
        [4.9000, 3.1000, 1.5000, 0.1000]])


In [40]:
print (labels_train[::10])

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 1, 0],
        [1, 0, 0]])


##  Neural Network

Criaremos uma rede que consiste em 3 camadas totalmente conectadas.

In [ ]:
# A camada de entrada recebe 4 valores de entrada (as features da íris) e aplica uma função de ativação ReLU.
# A camada oculta recebe dez entradas e aplica uma função de ativação ReLU.
# A camada de saída usa uma função de ativação do SoftMax para gerar 3 saídas (que representam as probabilidades para as três espécies de íris)

In [33]:
# Numeros dos nós da camada oculta
hl = 10

# Criando a rede neural
class IrisNet(nn.Module):
    def __init__(self):
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(4, hl)
        self.fc2 = nn.Linear(hl, hl)
        self.fc3 = nn.Linear(hl, 3)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.softmax(self.fc3(x),dim=1)
        return x

# Criando uma instancia do modelo da rede neural
model = IrisNet()
print(model)
loss_fn = nn.BCELoss() #calculates the loss
optim = torch.optim.SGD(model.parameters(), lr = 0.01)

IrisNet(
  (fc1): Linear(in_features=4, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
)


## Treinar o modelo

Para treinar o modelo, precisamos alimentar repetidamente os valores de treinamento pela rede, usar uma função de perda para calcular a perda, usar um otimizador para retropropagar os ajustes de peso e valor de polarização e validar o modelo usando os dados de teste que retivemos.

Para fazer isso, criaremos uma função para treinar e otimizar o modelo e a função para testar o modelo. Em seguida, chamaremos essas funções iterativamente por mais de 100 épocas, registrando as estatísticas de perda e precisão de cada época.

In [34]:
all_losses = []
for num in range(5000):
    pred = model(feature_train_v) #predict
    loss = loss_fn(pred, labels_train_v) #calculate loss
    all_losses.append(loss.data)
    optim.zero_grad() #zero gradients to not accumulate
    loss.backward() #update weights based on loss
    optim.step() #update optimiser for next iteration

In [39]:
#x_new = [[6.6,3.2,5.8,2.4]]
x_new = [[5.1,3.5,1.4,0.2]]
print ('New sample: {}'.format(x_new[0]))

model.eval()

# Get a prediction for the new data sample
x = torch.Tensor(x_new).float()
_, predicted = torch.max(model(x).data, 1)

print('Prediction:',iris_data.target_names[predicted.item()])

New sample: [5.1, 3.5, 1.4, 0.2]
Prediction: setosa
