## Tensors no PyTorch

Um tensor é um array ou vetor n-dimensional similar ao array do NumPy. Por exemplo, tensor-1d é um vetor, tensor-2d é uma matriz, tensor-3d é um cubo.

In [34]:
import torch
import numpy as np

In [6]:
# criando um tensor
new_tensor = torch.Tensor([[1, 2], [3, 4]])

In [7]:
new_tensor

tensor([[1., 2.],
        [3., 4.]])

In [8]:
# criando um tensor 2 x 3 com valores randomicos
rnd_tensor = torch.Tensor(2, 3)

In [9]:
rnd_tensor

tensor([[ 0.0000e+00, -8.5899e+09,  0.0000e+00],
        [-8.5899e+09,  8.4078e-45,  0.0000e+00]])

In [13]:
# criando um tensor 2 x 3 com valores randomicos entre -1 e 1
uniform_tensor = torch.Tensor(2, 3).uniform_(-1, 1)

In [15]:
uniform_tensor

tensor([[-0.1292, -0.5021, -0.0971],
        [-0.1011, -0.3931,  0.1821]])

In [16]:
# criando um tensor 2 x 3 de zeros
zero_tensor = torch.zeros(2, 3)

In [17]:
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [36]:
# usando numpy 
x1 = np.ones((3,3))

In [37]:
x1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# usando pytorch
t1 = torch.ones((3,3))

In [39]:
t1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## PyTorch & NumPy

As vezes, é útil converter um array do Numpy em um tensor do Pytorch e vice versa.

In [40]:
array_numpy = numpy.random.randn(2,2)

In [41]:
array_numpy

array([[-1.45337542, -1.62216657],
       [ 0.52463151,  0.15669416]])

In [42]:
# convertendo um array do NumPy em um Tensor do PyTorch
numpy2tensor = torch.from_numpy(array_numpy)

In [43]:
numpy2tensor

tensor([[-1.4534, -1.6222],
        [ 0.5246,  0.1567]], dtype=torch.float64)

In [44]:
# convertendo Tensor do PyTorch em um array do NumPy
tensor_to_ArrayNumpy = numpy2tensor.numpy()

In [45]:
tensor_to_ArrayNumpy

array([[-1.45337542, -1.62216657],
       [ 0.52463151,  0.15669416]])

## Operações Básicas com Tensor 

In [26]:
# criando tensors
tensor_1 = torch.randn(3, 3)
tensor_2 = torch.randn(3, 3)

In [27]:
tensor_1

tensor([[-0.3226, -0.4680,  0.7213],
        [-2.1117, -2.2548, -1.4227],
        [ 1.1696, -0.1642,  0.8407]])

In [28]:
# fazer uma matriz transposta
tensor_1.t()

tensor([[-0.3226, -2.1117,  1.1696],
        [-0.4680, -2.2548, -0.1642],
        [ 0.7213, -1.4227,  0.8407]])

In [29]:
# fazer o produto de matriz: .mm()
maxtriz_prod = tensor_1.mm(tensor_2)

In [30]:
maxtriz_prod

tensor([[-0.4989, -1.4786, -0.4525],
        [-3.4710, -1.1552,  0.6625],
        [ 0.6480, -1.0223,  1.0186]])